# Run 'testparm' to verify the config is correct after you modified it.

[global]
	workgroup = OCTAVIA
	security = user
	passdb backend = tdbsam
	printing = cups
	printcap name = cups
	load printers = yes
	cups options = raw
    unix extensions = no
	interfaces = lo 192.168.0.0/24
	bind interfaces only = yes
	hosts allow = 127. 192.168.0.

[shared]
	path = /home/rom/shared
	read only = yes
	guest ok = no
	browsable = yes
	wide links = yes
	vfs objects = widelinks
	valid users = rom

[printers]
	comment = All Printers
	path = /var/tmp
	printable = Yes
	create mask = 0600
	browseable = No

[print$]
	comment = Printer Drivers
	path = /var/lib/samba/drivers
	# printadmin is a local group
	write list = printadmin root
	force group = printadmin
